### ISSUE TITLE
NXM Handling errore

### ISSUE THREAD

**Issue by miramax001** [pikdum/vortex-linux#17]
Hi,

I'm using your Vortex install with Arch Linux (Garuda).

- Vortex 1.9.3
- ProtonGE 8.11

I've a problem with NXM handing, when the download start I get this error:

"Request URL https://api.nexusmods.com/v1/games/... failed with status 403"

![image](https://github.com/pikdum/vortex-linux/assets/106231529/fb45cc46-4772-4213-9404-ba103add5f9e)

If I copy/paste the nxm link in Vortex, the download everythings is ok (ex. nxm://nomanssky/mods/2828/files/26814?key=35La2FFsjxLXdl1JjRwQUw&expires=1692705968&user_id=1722218)

What I'm doing wrong?

**Comment by pikdum** [comment]
There's something broken about how this is handling downloads that makes it require premium.
How were you able to copy that nxm link?
That's the format it needs to be in (with the key), but I'm not finding an easy way to get at it.

**Comment by miramax001** [comment]
Hi, 
If I reject OPEN NXM on Vortex, I get this page with "Click here" 

with the following link: nxm://nomanssky/mods/2834/files/26844?key=kTdg1R9Gdgdzlw755usFUw&expires=1692787587&user_id=1722218

![image](https://github.com/pikdum/vortex-linux/assets/106231529/42358daf-50e5-47f4-a39f-284f1807ba9a)


If I click "Click here" inside browser and I let Vortex handle the link with NXM-Hanlder, Vortex fail with the error 403 
If I copy/paste the same link directly in Vortex, everything goes right...

**Comment by pikdum** [comment]
If you call through the CLI with that link, does it work?

```bash
vortex-linux launchVortex -d "nxm://nomanssky/mods/2834/files/26844?key=x&expires=x&user_id=x"
```

Or maybe with -i?

```bash
vortex-linux launchVortex -i "nxm://nomanssky/mods/2834/files/26844?key=x&expires=x&user_id=x"
```

**Comment by miramax001** [comment]
Hi,

with both "-d" and "-i"  parameters, i get the 403 error in Vortex

./vortex-linux launchVortex -- -d "nxm://nomanssky/mods/2828/files/26814?key=q9cl74sRA0IExyXcyijJzQ&expires=1692856416&user_id=1722218"

```
logging started

[2240:0822/075456.427:ERROR:network_change_notifier_win.cc(221)] WSALookupServiceBegin failed with: 0
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
```



./vortex-linux launchVortex -- -i "nxm://nomanssky/mods/2828/files/26814?key=q9cl74sRA0IExyXcyijJzQ&expires=1692856416&user_id=1722218"
```

logging started

[2416:0822/075521.420:ERROR:network_change_notifier_win.cc(221)] WSALookupServiceBegin failed with: 0
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
```

**Comment by pikdum** [comment]
~~Can you upgrade to https://github.com/pikdum/vortex-linux/releases/tag/v1.3.2 and try again?~~
~~This should log the whole command, so we can see what it's actually passing to Vortex.exe.~~

What about quoting it like this?

```
vortex-linux launchVortex -d "'nxm://nomanssky/mods/2834/files/26844?key=x&expires=x&user_id=x'"
```

I can't really think of anything else.

https://github.com/pikdum/vortex-linux/releases/tag/v1.3.4 adds quoting like that when opening with Vortex, but requires this to be re-ran to set up the desktop files:

```
vortex-linux setupVortexDesktop
```

Not sure if this will actually work, though, and if it doesn't then I'm out of ideas.

**Comment by miramax001** [comment]
IT WORKS!!!!!

```
./vortex-linux launchVortex -- -d "'nxm://nomanssky/mods/2828/files/26814?key=Urt-kaQlLXKlKAocMACY5w&expires=1692899924&user_id=1722218'"
Launching Vortex: "/home/danb/.vortex-linux/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe" -d 'nxm://nomanssky/mods/2828/files/26814?key=Urt-kaQlLXKlKAocMACY5w&expires=1692899924&user_id=1722218'

logging started

[1576:0822/200021.578:ERROR:network_change_notifier_win.cc(221)] WSALookupServiceBegin failed with: 0
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\steamuser\AppData\Local\openvr\openvrpaths.vrpath

```

As you already know, if I don't put the "--" before "-d"  it doesn't work:

```
/vortex-linux launchVortex -d "'nxm://nomanssky/mods/2828/files/26814?key=Urt-kaQlLXKlKAocMACY5w&expires=1692899924&user_id=1722218'"
error: unknown option '-d'
```

**Comment by miramax001** [comment]
https://github.com/pikdum/vortex-linux/releases/tag/v1.3.4 adds quoting like that when opening with Vortex, but requires this to be re-ran to set up the desktop files:

`vortex-linux setupVortexDesktop`

thanks @pikdum for the quick support :)
