### ISSUE TITLE
Baldurs Gate 3 - Error when deploying with 'Engine Injector' 

### ISSUE THREAD

**Issue by miramax001** [pikdum/vortex-linux#30]
Hi,

In BG3 there are some MODS that require to be installed OUTSIDE the normal MOD folder. (Ex. https://www.nexusmods.com/baldursgate3/mods/944)

Steps :
 - Download and Install this mod with Vortex.
 - Click 'Install as Replacer', ignore error and continue.
 -  Double click this mod
 -  Select 'Engine Injector' in 'Mod Type' dropdown !! Important
 -  Click the 'Deploy Mods' button, or 'Deploy' in the notification

At this point in the BG3/bin folder I should have 2 files:
 - bink2w64.dll
 - bink2w64_original.dll

Instead I have 1 file:
 - bink2w64.dll.vortex_backup

I'm missing something?

Thx :)

**Comment by pikdum** [comment]
I'm not familiar with BG3 modding and don't have the game, so I won't be much help here.

**Comment by miramax001** [comment]
Hi,

I could help, I can share with you the "basic" folder structure, so Vortex can recognize the game folder and you can do some test.

The problem is not related to BG3 but how Vortex handle the deployment of mods with "Engine Injector" in "Mod Type"


Let me know if we can proceed in this way

thanks

**Comment by pikdum** [comment]
Don't think that'll be enough, this is the first I've heard of Vortex handling different mod types differently too.
I'd recommend just doing the manual install method for this.

This installer doesn't really do anything more than getting Vortex set up, there still will be some weirdness to manually work around since the games and Vortex will be in separate wine prefixes.

Some examples of workarounds are the post-deploy scripts in https://github.com/pikdum/steam-deck for Bethesda games, or symlinks in general.

**Comment by miramax001** [comment]
Hi, 

this is the workaround that work for me:

1. as you suggested, I linked the vortex "compatdata" folder with the real one, used by Steam
```
rm -rf "$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/"
ln -s "$HOME/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3" "$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3"
```
2. Changed the deployment method with "Hardlink" or "Move"

So problem solved :)

- Can I close the Issue or you prefer some other digging into the problem?
- For the future issues, did you prefer that I post them on other repo? (https://github.com/pikdum/steam-deck)?


Thanks for you help!

**Comment by pikdum** [comment]
> Can I close the Issue or you prefer some other digging into the problem?

Can go ahead and close.

> For the future issues, did you prefer that I post them on other repo?

Here if you're using vortex-linux standalone, there if you're using those scripts on a steam deck.

> So problem solved :)

Nice. I might be able to use the symlink approach to make a pre-deploy script or similar in the steam deck repo.

**Comment by miramax001** [comment]
1. as you suggested, I linked the vortex "compatdata" folder with the real one, used by Steam
```
rm -rf "$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/"
ln -s "$HOME/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3" "$HOME/.vortex-linux/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3"
```
2. Changed the deployment method with "Hardlink" or "Move"

So problem solved :)
